- hosts: httpd
  tasks:
    - name: Configure SELinux to start mysql on any port
      ansible.posix.seboolean:
        name: mysql_connect_any
        state: true
        persistent: yes
      when: ansible_selinux.status == "enabled"
      # all variables can be used directly in conditionals without double curly braces


    - name: Shut down Debian flavored systems
      ansible.builtin.command: /sbin/shutdown -t now
      when: ansible_facts['os_family'] == "Debian"


    - name: Shut down CentOS 6 and Debian 7 systems
      ansible.builtin.command: /sbin/shutdown -t now
      when: (ansible_facts['distribution'] == "CentOS" and ansible_facts['distribution_major_version'] == "6") or
            (ansible_facts['distribution'] == "Debian" and ansible_facts['distribution_major_version'] == "7")



###################################################
    - name: Register a variable
      ansible.builtin.shell: cat /etc/motd
      register: motd_contents

    - name: Use the variable in conditional statement
      ansible.builtin.shell: echo "motd contains the word hi"
      when: motd_contents.stdout.find('hi') != -1


###################################################
    - name: List contents of directory
      ansible.builtin.command: ls mydir
      register: contents

    - name: Check contents for emptiness
      ansible.builtin.debug:
        msg: "Directory is empty"
      when: contents.stdout == ""

###################################################
    - name: Register a variable, ignore errors and continue
      ansible.builtin.command: /bin/false
      register: result
      ignore_errors: true

    - name: Run only if the task that registered the "result" variable fails
      ansible.builtin.command: /bin/something
      when: result is failed

    - name: Run only if the task that registered the "result" variable succeeds
      ansible.builtin.command: /bin/something_else
      when: result is succeeded

    - name: Run only if the task that registered the "result" variable is skipped
      ansible.builtin.command: /bin/still/something_else
      when: result is skipped

 ###################################################
    - name: Run with items greater than 5
      ansible.builtin.command: echo {{ item }}
      loop: [ 0, 2, 4, 6, 8, 10 ]
      when: item > 5