- hosts: httpd
  remote_user: root
  tasks:
  - name: Acquire temporary root password
    shell: "awk -F': ' '$0 ~ \"temporary password\"{print $2}' /var/log/mysqld.log"
    register: mysql_root_password_temp
    
  - name: Set new root password from default temporary password
    shell: "mysql -e \"SET PASSWORD = '{{ Abcde@12345 }}';\"
          --connect-expired-password -uroot -p'{{ mysql_root_password_temp.stdout }}'
          && touch /root/.my.password.changed"
    args:
      creates: /root/.my.password.changed

  - name: Removes anonymous user account for localhost
    mysql_user:
      name: ''
      host: localhost
      state: absent
